### ISSUE TITLE
Crashes on Linux using wine

### ISSUE THREAD

**Issue by AlexanderWKoenig** [saynotosync/Matrix-PON-Framerate-Fix#2]
Hi,
when running this framerate fix via wine on linux, the game crashes before showing anything.
This is the console output
WINE VERSION = wine-6.21-182-g3dbce69fd4c
0148:err:virtual:virtual_setup_exception stack overflow 1284 bytes in thread 0148 addr 0x7bc52d48 stack 0x230afc (0x230000-0x231000-0x330000)

Any ideas why this fix crashes with wine? If I set FixFrameRate = 0 the game is working with widescreen fix.

**Comment by adc-ax** [comment]
This is likely due to additional interaction with process memory that I’m doing to adjust framerate-related values on top of the original widescreen fix. Windows is probably more lenient in this regard. This is my first patch of this kind, so I’ll have to do a bit more research on process hooking / writing to process memory to do things in a cleaner way. Thanks for bringing this to my attention.

**Comment by adc-ax** [comment]
@AlexanderWKoenig could you please tell me the exact size of your "Matrix3W32S.bin" file? I want to check whether I have a different version of the game (with a differently compiled binary, which would be kind of weird, but I don't think it'd hurt to check).

**Comment by adc-ax** [comment]
This issue seems to be endemic to the 1.2 cracked .bin from Deviance group (23,052,288 bytes in size) specifically, as that was the only binary that presented me with it.

**Comment by adc-ax** [comment]
@AlexanderWKoenig Fixed in the latest version of the script.

**Comment by AlexanderWKoenig** [comment]
Thanks a lot for this fix. So far it is running well on linux with wine.
